Ev 6 redesign about page
ita-social-projects/EventsExpress-Frontend pull request #108
Opened 2022-05-22 09:04 UTC by Melenko55

dev
## GitHub Project

* [Main GitHub Project ticket](https://github.com/ita-social-projects/EventsExpress-Frontend/projects/1)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2022-05-25 10:15 UTC, Danyil-man approved these changes, later dismissed

2022-05-25 16:53 UTC, StodolaNazariy submitted a review, later dismissed
Молодець))

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.jsx
> +// };
Why you comment it?

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.jsx
> +// };
Why you comment it?

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.jsx
> +// import PropTypes from "prop-types";
Why you comment it?

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.jsx
> -import aboutImg5 from "../../assets/images/aboutUs/aboutImg-5.png";
Move to diff file

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.jsx
>  ];
the same as above

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.jsx
>  };
Refactor it, reduce extra tag

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +  max-width: 50%;
use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +    font-weight: bold;
use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +    font-size: 24px;
use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +      url("https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&
use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +    width: 100%;
use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +        font-size: 60px;
use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +        font-weight: bold;
use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +          box-shadow: 0px 5px 55px $lightPink;
use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +    width: 100%;
use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +      width: 100%;
use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +        width: calc(100% / 4);
25%?

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +          height: 100%;
use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +          left: 50%;
use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +          transform: translate(-50%, -50%);
use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +          font-size: 2.5rem;
try to use px and use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +      width: 100%;
use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +      font-weight: bold;
use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +        width: 100%;
use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +          img {
do not use tag

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +            border-radius: 100%;
use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +          width: 100%;
use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +            font-size: 36px;
use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +            font-weight: bold;
use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +            font-size: 18px;
use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +    .info-text__body {
Can use short view

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +      font-size: 20px;
use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +    max-width: 100%;
use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +      font-size: 36px;
use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +      font-size: 20px;
use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +      font-weight: bold;
use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +        .banner-content__quote {
Can use short view

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +          font-size: 45px;
use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +          font-size: 20px;
use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +          .info-images__text {
Can use short view

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +            font-size: 24px;
use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +            transform: translate(-50%, -50%);
use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +        width: 100%;
use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +      .members-title {
Can use short view

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +        font-size: 36px;
use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +        .member {
Can use short view

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +              font-size: 24px;
use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +              font-size: 16px;
use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
>  }
Do not abuse nesting

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +      .banner-content {
Can use short view

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +        width: 100%;
use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +          font-size: 40px;
use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +      font-size: 16px;
use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +      font-size: 30px;
use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +        width: 100%;
use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +          font-size: 30px;
use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +          font-size: 16px;
use constants

2022-05-26 07:29 UTC, andrii-kuzmichov commented on src/components/SplitPanels/SplitPanels.jsx
> +          " ",
use template literal

2022-05-26 07:30 UTC, andrii-kuzmichov requested changes
Fix all comments

2022-05-29 10:13 UTC, Danyil-man approved these changes, later dismissed

2022-05-29 10:13 UTC, Danyil-man commented on src/components/AboutUs/AboutUs.scss
> +    border-radius: 20px;
const for border radius

2022-05-31 06:12 UTC, PopowychSasha submitted a review, later dismissed

2022-05-31 08:07 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutContent.js
> +import aboutImg1 from "../../assets/images/aboutUs/aboutImg-1.png";
Move this file to constants

2022-05-31 08:07 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutContent.js
> +} = constants;
change to specific import

2022-05-31 08:07 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.jsx
>    return (
drop return

2022-05-31 08:07 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.jsx
> +      <div className="about-members">
move to diff component

2022-05-31 08:07 UTC, andrii-kuzmichov commented on src/components/AboutUs/AboutUs.scss
> +@import "../../styles/pages/about.scss";
Check it out

2022-05-31 08:07 UTC, andrii-kuzmichov commented on src/components/AboutUs/InfoSection/InfoSection.jsx
> +
empty line

2022-05-31 08:07 UTC, andrii-kuzmichov commented on src/components/AboutUs/Members/Members.jsx
> +          <div className="member__image-container">
extra div

2022-05-31 08:07 UTC, andrii-kuzmichov commented on src/styles/mixins.scss
> +  transform: translate(-50%, -50%);
use constants

2022-05-31 13:48 UTC, andrii-kuzmichov approved these changes

2022-05-31 14:35 UTC, merged