Update event card
ita-social-projects/EventsExpress-Frontend pull request #109
Opened 2022-05-24 07:07 UTC by na3alis

dev
## GitHub Project

* [Main GitHub Project ticket](https://github.com/ita-social-projects/EventsExpress-Frontend/projects/1)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2022-05-25 08:59 UTC, MelenkoOleksandr requested changes
EventlListCard.scss - Put fonts in fonts.scss file and then import them
SliderForEvents.scss - something wrong with import

2022-05-28 12:02 UTC, MelenkoOleksandr commented on src/components/landing/EventsListItem/EventListCard/EventListCard.scss
>          box-shadow: 10px 10px 40px 0 rgba(0, 0, 0, 0.75);
use constants))

2022-05-30 16:46 UTC, StodolaNazariy commented on src/components/landing/EventCard/EventCard.js
> +        </div>
if block has only 1 child, u don`t need extra wrapper
we discussed it

2022-05-30 16:46 UTC, ghost commented on src/components/landing/EventCard/EventCard.scss
> +    width: 100%;
use constants

2022-05-30 16:46 UTC, StodolaNazariy commented on src/components/landing/EventCard/EventCard.scss
> +    align-items: center;
use mixin

2022-05-30 16:47 UTC, StodolaNazariy commented on src/components/landing/EventCard/EventCard.scss
> +        align-items: center;
use mixin

2022-05-30 16:48 UTC, StodolaNazariy commented on src/components/landing/EventCard/EventCard.scss
> +          align-items: center;
use mixin

2022-05-30 16:48 UTC, StodolaNazariy commented on src/components/landing/EventCard/EventCard.scss
> +          font-size: 80px;
use constant or mixin

2022-05-30 16:48 UTC, StodolaNazariy commented on src/components/landing/EventCard/EventCard.scss
> +        font-size: 14px;
use constants

2022-05-30 16:49 UTC, StodolaNazariy commented on src/components/landing/EventCard/EventCard.scss
> +        align-items: center;
use mixin

2022-05-30 16:49 UTC, StodolaNazariy commented on src/components/landing/EventCard/EventCard.scss
> +          align-items: center;
use mixin

2022-05-30 16:49 UTC, StodolaNazariy commented on src/components/landing/EventCard/EventCard.scss
> +    width: 100%;
use constant

2022-05-30 16:50 UTC, StodolaNazariy commented on src/components/landing/EventsListItem/EventListCard/EventListCard.scss
> +    justify-content: center;
use mixin

2022-05-30 16:50 UTC, StodolaNazariy commented on src/components/landing/EventsListItem/EventListCard/EventListCard.scss
> +          align-items: center;
use mixin

2022-05-30 16:51 UTC, StodolaNazariy commented on src/components/landing/EventsListItem/EventListCard/EventListCard.scss
> +      align-items: center;
use mixin

2022-05-30 16:51 UTC, StodolaNazariy commented on src/components/landing/EventsListItem/EventListCard/EventListCard.scss
> +          font-size: 100px;
use constants or mixin

2022-05-30 16:51 UTC, StodolaNazariy commented on src/components/landing/EventsListItem/EventListCard/EventListCard.scss
> +          font-size: 45px;
use constants

2022-05-30 16:52 UTC, StodolaNazariy commented on src/components/landing/EventsListItem/EventListCard/EventListCard.scss
> +            font-size: 13px;
use constants

2022-05-30 16:52 UTC, StodolaNazariy commented on src/components/landing/EventsListItem/EventListCard/EventListCard.scss
> +            font-size: 80px;
use constants

2022-05-30 16:53 UTC, StodolaNazariy commented on src/components/landing/SliderForEvents/settingsForSlider.js
> +      breakpoint: 1180,
magic number

2022-05-30 16:53 UTC, StodolaNazariy commented on src/components/landing/SliderForEvents/settingsForSlider.js
> +      breakpoint: 767,
magic number

2022-05-30 16:53 UTC, StodolaNazariy commented on src/components/landing/SliderForEvents/settingsForSlider.js
>    speed: 500,
magic number

2022-05-31 07:30 UTC, andrii-kuzmichov reviewed
Drop all specific measures

2022-05-31 07:30 UTC, andrii-kuzmichov commented on src/actions/event/event-list-action.js
>      const jsonRes = await response.json();
rename to data

2022-05-31 07:30 UTC, andrii-kuzmichov commented on src/components/landing/EventCard/EventCard.js
> +  ];
Move to constants

2022-05-31 07:30 UTC, andrii-kuzmichov commented on src/components/landing/EventCard/EventCard.js
> +  const monthIndex = moment(dateFrom).format("M") - 1;
Move `M` to constatns as format date obj

2022-05-31 07:30 UTC, andrii-kuzmichov commented on src/components/landing/EventCard/EventCard.js
> +    });
move to service

2022-05-31 07:30 UTC, andrii-kuzmichov commented on src/components/landing/EventCard/EventCard.js
> +        <div className="card-date date-container">
extra div

2022-05-31 07:30 UTC, andrii-kuzmichov commented on src/components/landing/EventCard/EventCard.js
> +          <span className="day">{moment(dateFrom).format("DD")}</span>
move `DD` to format date constants

2022-05-31 07:30 UTC, andrii-kuzmichov commented on src/components/landing/EventCard/EventCard.js
> +            {title.length > 35 ? `${title.slice(0, 35)}...` : title}
Strange logic move to utils

2022-05-31 07:30 UTC, andrii-kuzmichov commented on src/components/landing/EventCard/EventCard.js
> +              <BiRightArrowAlt size={30} />
`30` move to constants

2022-05-31 07:30 UTC, andrii-kuzmichov commented on src/components/landing/EventCard/EventCard.js
> +      <span className="month">{monthes[monthIndex]}</span>
Refactoring logic

2022-05-31 07:30 UTC, andrii-kuzmichov commented on src/components/landing/EventCard/EventCard.scss
> +  box-shadow: $distance10px $distance10px $distance20px 0 $lightThemeHeader;
remove specific for distance and create or reuse for box-shadow

2022-05-31 07:30 UTC, andrii-kuzmichov commented on src/components/landing/EventCard/EventCard.scss
> +        font-weight: bold;
constants

2022-05-31 07:30 UTC, andrii-kuzmichov commented on src/components/landing/EventCard/EventCard.scss
> +        font-weight: bold;
the same

2022-05-31 07:30 UTC, andrii-kuzmichov commented on src/components/landing/EventCard/EventCard.scss
> +    font-family: 'Robinson', sans-serif;
use constants

2022-05-31 07:30 UTC, andrii-kuzmichov commented on src/components/landing/EventCard/IconsEventCard/IconsEventCard.scss
> +  background: url("../../../../assets/icons/ImgJoinToEvent.svg") no-repeat center;
constants

2022-05-31 07:30 UTC, andrii-kuzmichov commented on src/components/landing/EventMatrix/EventMatrix.js
>    return (
drop return

2022-05-31 07:30 UTC, andrii-kuzmichov commented on src/components/landing/EventsListItem/EventListCard/EventListCard.js
> +  ];
Drop

2022-05-31 07:30 UTC, andrii-kuzmichov commented on src/components/landing/EventsListItem/EventListCard/EventListCard.js
> +        setEventImage(image);
move to service

2022-05-31 07:30 UTC, andrii-kuzmichov commented on src/components/landing/EventsListItem/EventListCard/EventListCard.js
>  import React, { useState, useEffect } from "react";
Try to create unified component for this and above

2022-05-31 07:30 UTC, andrii-kuzmichov commented on src/components/landing/EventsListItem/EventListCard/EventListCard.scss
> +          font-weight: bold;
constants

2022-05-31 07:30 UTC, andrii-kuzmichov commented on src/components/landing/EventsListItem/EventListCard/EventListCard.scss
> +          font-weight: bold;
constants

2022-05-31 07:30 UTC, andrii-kuzmichov commented on src/components/landing/EventsListItem/EventListCard/EventListCard.scss
> +          font-family: 'Robinson', sans-serif;
constants

2022-05-31 07:30 UTC, andrii-kuzmichov commented on src/components/landing/EventsListItem/EventListCard/EventListCard.scss
> +          font-weight: bold;
constants

2022-05-31 07:30 UTC, andrii-kuzmichov commented on src/components/landing/EventsListItem/EventListCard/EventListCard.scss
> +          text-shadow: 0 0 $distance20px $white;
constants

2022-05-31 07:30 UTC, andrii-kuzmichov commented on src/components/landing/EventsListItem/EventListCard/EventListCard.scss
> +          font-size: $distance45px;
typo

2022-05-31 07:30 UTC, andrii-kuzmichov commented on src/components/landing/EventsListItem/EventListCard/EventListCard.scss
> +            font-size: 12px;
constants

2022-05-31 07:30 UTC, andrii-kuzmichov commented on src/components/landing/EventsListItem/EventListCard/EventListCard.scss
> +            font-size: 12px;
constants

2022-05-31 07:30 UTC, andrii-kuzmichov commented on src/components/landing/EventsListItem/EventListCard/EventListCard.scss
> +            font-family: 'Robinson', sans-serif;
constants

2022-05-31 07:30 UTC, andrii-kuzmichov commented on src/components/landing/EventsListItem/EventListCard/EventListCard.scss
> +            font-weight: bold;
constants

2022-05-31 07:30 UTC, andrii-kuzmichov commented on src/components/landing/EventsListItem/EventListCard/EventListCard.scss
> +            text-shadow: 0 0 $distance20px $white;
constants

2022-05-31 07:30 UTC, andrii-kuzmichov commented on src/components/landing/EventsListItem/EventListCard/EventListCard.scss
> +            font-size: $distance80px;
typo

2022-05-31 07:30 UTC, andrii-kuzmichov commented on src/components/landing/EventsListItem/EventListCard/EventListCard.scss
> +            font-size: 40px;
constants

2022-05-31 07:30 UTC, andrii-kuzmichov commented on src/components/landing/EventsListItem/EventListCard/EventListCard.scss
> +            text-shadow: 0 0 $distance10px $lightThemeHeader;
constants

2022-05-31 07:30 UTC, andrii-kuzmichov commented on src/components/landing/EventsListItem/EventListCard/EventListCard.scss
> +            font-weight: bold;
constants

2022-05-31 07:30 UTC, andrii-kuzmichov commented on src/components/landing/EventsListItem/EventListCard/EventListCard.scss
> +            font-size: $distance70px;
typo

2022-05-31 07:30 UTC, andrii-kuzmichov commented on src/components/landing/EventsListItem/EventListCard/EventListCard.scss
> +            font-size: $distance40px;
typo

2022-05-31 07:30 UTC, andrii-kuzmichov commented on src/components/landing/EventsListItem/EventsListItem.js
> +  events.map(event => <EventListCard key={event.id + 5} event={event} />);
magic number

2022-05-31 07:30 UTC, andrii-kuzmichov commented on src/components/landing/SliderForEvents/SliderForEvents.scss
> +  width: $distance25px;
bad name

2022-05-31 07:30 UTC, andrii-kuzmichov commented on src/styles/_variables.scss
> +$lightPink: #E4D5EE;
use small case

2022-05-31 07:30 UTC, andrii-kuzmichov commented on src/styles/_variables.scss
> +$lightPink: #E4D5EE;
Maybe should be used in colors.scss

2022-05-31 12:04 UTC, MelenkoOleksandr approved these changes, later dismissed

2022-05-31 12:06 UTC, Danyil-man approved these changes, later dismissed

2022-05-31 13:51 UTC, andrii-kuzmichov approved these changes, later dismissed

2022-05-31 16:57 UTC, andrii-kuzmichov approved these changes, later dismissed

2022-05-31 19:43 UTC, andrii-kuzmichov approved these changes, later dismissed

2022-05-31 19:51 UTC, andrii-kuzmichov approved these changes

2022-05-31 19:57 UTC, merged