Ev 12 : refactoring user menu in header
ita-social-projects/EventsExpress-Frontend pull request #111
Opened 2022-05-26 21:51 UTC by PopowychSasha

### Jira

* [EV-12](refactoring user menu in header)

### Description
changed the styles in the drop-down menu and also added icons to each menu item

### Summary of change
dropdownMenu.js
dropdownMenu.scss

### Checklist

- [x] Includes a link to JIRA ticket and all related PR (API dependencies etc.)
- [x] Includes a brief description of what has been changed
- [x] Test coverage for **new** code doesn't decrease the existing test coverage
- [x] Lint errors/warnings fixed
- [x] New code is documented if necessary
- [x] Dev Testing has been successfully finished
- [x] Reviewed by 2 developer on your team
- [x] Reviewed by 1 expert

2022-05-26 21:56 UTC, StodolaNazariy commented on src/components/Header/BurgerMenu/BurgerMenuLink.jsx
> +      <div className="burger-line"></div>
use map instead of 3 divs

2022-05-26 21:57 UTC, PopowychSasha commented on src/components/Header/BurgerMenu/BurgerMenuLink.jsx
> +
1234

2022-05-28 11:47 UTC, MelenkoOleksandr commented on src/components/Header/BurgerMenu/BurgerMenuLink.scss
> +@import "../../../styles/main.scss";
import only that files that you use

2022-05-28 11:48 UTC, MelenkoOleksandr commented on src/components/Header/HeaderLinks/HeaderLinks.scss
> +    font-weight: 700;
Add existing font weight from fonts.scss

2022-05-28 11:48 UTC, MelenkoOleksandr commented on src/components/Header/HeaderLinks/HeaderLinks.scss
> +    font-weight: 700;
Add existing font weight from fonts.scss

2022-05-28 11:49 UTC, MelenkoOleksandr commented on src/components/Header/HeaderLinks/HeaderLinks.scss
> +    font-weight: 700;
Add existing font weight from fonts.scss

2022-05-28 11:49 UTC, MelenkoOleksandr commented on src/components/Header/HeaderLinks/HeaderLinks.scss
> +    font-size: 18px;
Use constants

2022-05-28 11:49 UTC, MelenkoOleksandr commented on src/components/Header/HeaderLinks/HeaderLinks.scss
> +    font-size: 18px;
use contsants

2022-05-28 11:50 UTC, MelenkoOleksandr commented on src/components/Header/HeaderLinks/HeaderLinks.scss
> +    img {
dont use tags

2022-05-28 11:50 UTC, MelenkoOleksandr commented on src/components/Header/HeaderLinks/HeaderLinks.scss
> +    li {
dont use tags

2022-05-28 11:50 UTC, MelenkoOleksandr commented on src/components/Header/HeaderLinks/HeaderLinks.scss
> +    img {
dont use tags

2022-05-28 11:50 UTC, MelenkoOleksandr commented on src/components/Header/HeaderLinks/HeaderLinks.scss
> +  li {
dont use tags

2022-05-28 11:51 UTC, MelenkoOleksandr commented on src/components/Header/MobileHeaderLinks/MobileHeaderLinks.scss
> +        font-weight: 700;
Use constants

2022-05-28 11:51 UTC, MelenkoOleksandr commented on src/components/Header/MobileHeaderLinks/MobileHeaderLinks.scss
> +    width: 100vw;
Use constants

2022-05-28 11:57 UTC, MelenkoOleksandr requested changes

2022-05-28 11:57 UTC, MelenkoOleksandr commented on src/components/Header/MobileHeaderLinks/MobileHeaderLinks.scss
> +    height: 100vh;
Use constants

2022-05-28 11:57 UTC, MelenkoOleksandr commented on src/components/Header/dropdownMenu/dropdownMenu.scss
> +  align-items:center;
You have mixin for this in mixins.scss

2022-05-28 11:57 UTC, MelenkoOleksandr commented on src/components/Header/dropdownMenu/dropdownMenu.scss
> +  div {
dont use tags. Or use in global.scss

2022-05-28 11:57 UTC, MelenkoOleksandr commented on src/components/Header/headerRightBlock/headerRightBlock.js
> +  window.addEventListener("resize", () => {
move to useEffect

2022-05-28 11:57 UTC, MelenkoOleksandr commented on src/components/Header/headerRightBlock/headerRightBlock.scss
> +  font-weight: 700;
use constants

2022-05-28 11:57 UTC, MelenkoOleksandr commented on src/components/shared/Logo/logo.scss
> +    text-shadow: 0 0 3px $gray, 0 0 5px $lightThemeAccept;
create variable for shadow

2022-05-30 06:14 UTC, andrii-kuzmichov approved these changes

2022-05-31 07:29 UTC, merged