Ev-16 refactoring user profile page
ita-social-projects/EventsExpress-Frontend pull request #130
Opened 2022-06-16 22:39 UTC by PopowychSasha

### Jira

* [EV-16]

### Description

changed the structure of the Profile.jsx component and also changed the components in the Profile / EditProfile folder

### Checklist

- [x] Includes a link to JIRA ticket and all related PR (API dependencies etc.)
- [x] Includes a brief description of what has been changed
- [x] Test coverage for **new** code doesn't decrease the existing test coverage
- [x] Lint errors/warnings fixed
- [x] New code is documented if necessary
- [x] Dev Testing has been successfully finished
- [x] Reviewed by 2 developer on your team
- [x] Reviewed by 1 expert

2022-06-17 13:05 UTC, ghost commented on src/components/Profile/EditProfile/ChangeAvatar.jsx
> +        disabled={pristine || submitting || invalid}
In which case this button will be disabled?

2022-06-17 13:07 UTC, StodolaNazariy commented on src/components/Profile/EditProfile/ChangePassword.jsx
>        expanded={expanded === "panel5"}
use constatnts

2022-06-17 13:10 UTC, StodolaNazariy commented on src/components/Profile/EditProfile/LinkedAuths.jsx
> +    element = <i className="fab fa-twitter" />;
it would be much better written via object and his keys

2022-06-17 13:10 UTC, StodolaNazariy commented on src/components/Profile/Profile.jsx
>  import { makeStyles } from "@material-ui/core/styles";
avoid using makeStyles

2022-06-17 13:11 UTC, StodolaNazariy commented on src/components/Profile/Profile.jsx
> +    marginTop: "100px",
drop makeStyles

2022-06-17 13:11 UTC, ghost commented on src/components/Profile/Profile.jsx
> +export default connect(mapStateToProps, mapDispatchToProps)(Profile);
move it into containers

2022-06-17 13:15 UTC, StodolaNazariy requested changes
Drop makeStyles and refactor

2022-06-20 06:34 UTC, StodolaNazariy approved these changes

2022-06-20 06:54 UTC, LisovyiNazar approved these changes

2022-06-20 16:24 UTC, closed without merging