Fix lint conteiners reducers and services
ita-social-projects/EventsExpress-Frontend pull request #32
Opened 2022-01-31 17:31 UTC by LesiaM-T

dev
## GitHub Project

* [Main GitHub Project ticket](https://github.com/ita-social-projects/EventsExpress-Frontend/projects/1)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

fixed linter plroblems in some containers, reducers and services
## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2022-01-31 19:49 UTC, VadymKharyton reviewed
Please change PR base branch, because there are a lot of changes, and I'm not able to identify exactly your changes

2022-01-31 19:59 UTC, LesiaM-T commented
> Please change PR base branch, because there are a lot of changes, and I'm not able to identify exactly your changes

Sorry, made it by mistake. Now changed the base.

2022-01-31 20:22 UTC, Vladosik12333 requested changes

2022-01-31 20:22 UTC, Vladosik12333 commented on package.json
>  	"dependencies": {
Delete changes in package.json

2022-01-31 20:22 UTC, Vladosik12333 commented on src/containers/unitsOfMeasuring/unitOfMeasuring-item.js
>    item: PropTypes.object,
You have propTypes on 96 line. Why you use two propTypes, you need only one. Transfer these propTypes in propTypes on 96 line.

2022-01-31 20:22 UTC, Vladosik12333 commented on src/reducers/hub.js
> +      state.chatHub.invoke("EventWasCreated", action.payload).catch(err => err);
Write TODO: Make error handling.

2022-01-31 20:22 UTC, Vladosik12333 commented on src/reducers/root.js
> +import * as LoginReducer from "./login";
Do you sure this work? If LoginReducer return not default, you will need `{... as ...}`.

2022-01-31 20:22 UTC, Vladosik12333 commented on src/services/EventsExpressService.js
> +    const call = (url, Data) =>
Why you write Data from big letter? If you need another parameters from function setResource, you will write callUrl and callData.

2022-01-31 20:22 UTC, Vladosik12333 commented on src/services/EventsExpressService.js
>    setResource = async (Url, data) => {
`Url` must be `url`.

2022-01-31 20:22 UTC, Vladosik12333 commented on src/services/InventoryService.js
>      await baseService.setResource(`UserEventInventory/Delete`, data);
If you write dataCopy instead of data, you will need write dataCopy in here.

2022-01-31 20:35 UTC, LesiaM-T commented on package.json
>  	"dependencies": {
i need to add "react-router"

2022-01-31 20:37 UTC, Vladosik12333 commented on package.json
>  	"dependencies": {
Ohh.. yes.

2022-01-31 20:49 UTC, LesiaM-T commented on src/services/EventsExpressService.js
>    setResource = async (Url, data) => {
specify, please, wich row you mean?

2022-01-31 20:55 UTC, Vladosik12333 commented on src/services/EventsExpressService.js
>    setResource = async (Url, data) => {
34

2022-02-01 13:01 UTC, Vladosik12333 commented on src/services/EventsExpressService.js
>    getPhoto = async Url => {
Url must be lower case.
Write `url` instead `Url` in full file and rename some vars (example: url -> callUrl).

2022-02-01 13:02 UTC, Vladosik12333 commented on src/services/InventoryService.js
> +    const dataCopy = data;
Must write `const dataCopy = {...data}`

2022-02-01 13:40 UTC, Vladosik12333 approved these changes

2022-02-01 13:41 UTC, merged